### ISSUE TITLE
Find machine parameters automatically

### ISSUE THREAD

**Issue by ribalba** [green-coding-solutions/spec-power-model#21]
A lot of the parameters that you can supply could be found by the script automatically. Like:

- CPU Chips [integer [1,)]
- CPU Threads [integer [1,)]
- CPU Cores [integer [1,)]
- CPU Frequency [integer [1,)]
- Architecture [str]
- CPU Make [str]
- Release year [int]
- RAM [integer (0,]]
- TDP [integer (0,]]

We could probably just populate them when running the script. Or have a parameter `--auto`. 
ChatGPT gives me a good starting point:
```
import os
import subprocess
import re

def get_cpu_info():
    # CPU Chips, Threads, Cores, and Frequency
    cpuinfo = subprocess.check_output("lscpu", shell=True).strip().decode()
    
    chips = int(subprocess.check_output("lscpu | grep 'Socket(s):' | awk '{print $2}'", shell=True).strip())
    threads = int(subprocess.check_output("lscpu | grep 'Thread(s) per core:' | awk '{print $4}'", shell=True).strip()) * \
              int(subprocess.check_output("lscpu | grep 'Core(s) per socket:' | awk '{print $4}'", shell=True).strip()) * chips
    cores = int(subprocess.check_output("lscpu | grep 'Core(s) per socket:' | awk '{print $4}'", shell=True).strip()) * chips
    frequency = int(float(subprocess.check_output("lscpu | grep 'MHz' | awk '{print $3}'", shell=True).strip()))

    # Architecture
    architecture = subprocess.check_output("uname -m", shell=True).strip().decode()

    # CPU Make (This might not always give accurate results)
    cpu_make = subprocess.check_output("cat /proc/cpuinfo | grep 'model name' | uniq | awk -F ': ' '{print $2}'", shell=True).strip().decode()

    # Release Year and TDP are difficult to obtain programmatically
    release_year = "Unknown"
    tdp = "Unknown"

    # RAM
    meminfo = subprocess.check_output("cat /proc/meminfo | grep MemTotal", shell=True).strip().decode()
    ram = int(re.findall(r'\d+', meminfo)[0]) // 1024  # Convert to MB

    return {
        "CPU Chips": chips,
        "CPU Threads": threads,
        "CPU Cores": cores,
        "CPU Frequency (MHz)": frequency,
        "Architecture": architecture,
        "CPU Make": cpu_make,
        "Release Year": release_year,
        "RAM (MB)": ram,
        "TDP": tdp
    }

if __name__ == "__main__":
    info = get_cpu_info()
    for key, value in info.items():
        print(f"{key}: {value}")
```

Maybe we can use something like https://www.techpowerup.com/cpu-specs/ to find the TDP

**Comment by ArneTR** [comment]
The problem why this was not implemented in the first place is that sometimes these values cannot be found.

lscpu and lsmem are often not available depending on the VM. /proc/cpuinfo i have so far always seen, but it has no information about the sockets.

The question is then for me: What good is the auto mode if it just can find some values or in rare cases none at all. Is that a feature that should be implemented?

And if so: How shall it fail? Should it fail fully and say that only 1-2 values can be detected.

Pro argument is: It will work for sure under native linux boxes. But will probably flake everywhere else.

**Comment by ribalba** [comment]
Maybe we can add a parameter/ script that finds what it can and shows it. Currently the user needs to find out these values by hand.

**Comment by ArneTR** [comment]
The more I think about it the more I like it. Will take this on.
